name: Artificial Intelligence - infrastructure - data
type: Tech-1
data:
  github_repo:
    - 250213286 # repo:huggingface/datasets
    - 290621741 # repo:EleutherAI/The-Pile
    - 184690694 # repo:openai/gpt-2-output-dataset
    - 685189532 # repo:openai/compose-richtext
    - 171325281 # repo:jcpeterson/openwebtext
    - 264870386 # repo:openai/gpt-3
    - 627636169 # repo:allenai/mmc4
    - 622196323 # repo:FreedomIntelligence/LLMZoo
    - 650086239 # repo:X-PLUG/Youku-mPLUG
    - 678206546 # repo:opendatalab/WanJuan1.0
    - 656099147 # repo:embedchain/embedchain